"""LLM prover: theorem -> reasoning trace + Submission.lean."""

from __future__ import annotations

import json
from typing import Protocol, TypeVar

import httpx
from loguru import logger
from openai import AsyncOpenAI

from lemma.common.async_llm_retry import (
    TRANSIENT_OPENAI_COMPAT,
    anthropic_async_client_cls,
    anthropic_transient_exceptions,
    async_llm_retry,
)
from lemma.common.config import LemmaSettings
from lemma.protocol import LemmaChallenge, ReasoningStep
from lemma.reasoning.format import format_reasoning_steps

T = TypeVar("T")


def _httpx_timeout(settings: LemmaSettings) -> httpx.Timeout:
    """Long **read** budget for one completion; short connect so failures surface quickly."""
    read_s = float(settings.llm_http_timeout_s)
    write_s = min(600.0, max(60.0, read_s))
    return httpx.Timeout(connect=30.0, read=read_s, write=write_s, pool=30.0)


class Prover(Protocol):
    async def solve(self, synapse: LemmaChallenge) -> tuple[str, str, list[ReasoningStep] | None]:
        """Return (reasoning_trace, proof_script, optional structured steps)."""


_STUDIO_CLIENT_SUBSTR = "gen-lang-client"


def _raise_if_prover_model_is_studio_client_id(model: str | None) -> None:
    """Gemini 404s often mean PROVER_MODEL was set to an AI Studio internal id by mistake."""
    if model and _STUDIO_CLIENT_SUBSTR in model.lower():
        raise ValueError(
            "PROVER_MODEL looks like a Google AI Studio internal id (gen-lang-client-…), not a model name. "
            "Set PROVER_MODEL to a public Gemini id, e.g. gemini-2.0-flash — see "
            "https://ai.google.dev/gemini-api/docs/models"
        )


PROVER_SYSTEM = """You are an expert Lean 4 prover. The user message has only two parts: (1) "Imports hint"
— the suggested Mathlib/modules list for this challenge — and (2) "Theorem block" — the exact Lean source
you must prove. No other hints, labels, or hidden steps are sent; you must infer the full argument yourself.

Return ONLY a JSON object (no markdown fences) with keys:
- "reasoning_steps": array of objects, each with "text" (string, required) and optional "title" (short label).
  Give informal reasoning as a true step-by-step walkthrough: plain English, logical order, no analogies
  to unrelated real-world stories (e.g. no "think of it like shopping / sports"). Explain the mathematical
  logic directly (what each case does, what each calc line accomplishes, what definitions or lemmas mean in
  this context). In-depth is preferred over artificially short summaries; thousands of characters of
  substantive explanation are encouraged.

  **Split contract — formal Lean vs informal teaching:** These are **two jobs**. (1) **`proof_script`** must be
  **correct Lean** that builds against Mathlib: using named lemmas, `simp`, `rw`, `ring`, and short `exact` chains
  when they match the goal is **expected** and keeps proofs from breaking — "Lemma" in the subnet sense is about
  proved statements; Mathlib **lemmas** in Lean are fair game. (2) **`reasoning_steps`** must **always** carry real
  pedagogy for a **lay reader**: step-by-step intuition, what notation means in words, optional tiny numeric
  examples, and (when the formal script cites a lemma) a plain-language account of **what** that lemma says and
  **why** it applies — including equality direction if relevant. **Never** shorten informal depth because the formal
  proof is a few lines; never substitute meta-commentary ("we used the library instead of hand-proof") for mathematics.

  Compliance (informal layer — applies even when the formal proof is one tactic or uses library lemmas):
  - **Address the math, not the autogenerated name:** Explain the **theorem as stated** (quantifiers, types,
    inequality/equality, key operators like `abs`, `dist`, etc.) in plain language. **Do not** build the
    narrative around the internal `theorem` identifier (e.g. `t_9f40c8`); treat that as a label for Lean only.
    A lay reader cares about the **formal goal** (what is being proved), not the hash-like name.
  - Do NOT compress the narrative because the proof is "easy". Every problem gets the same standard of
    exposition: restate the goal in words, name the proof strategy, cite Mathlib lemmas by name when you
    use them, and explain how the formal proof lines realize that strategy (including direction of equalities,
    why symm/rewrite applies, etc.).
  - **No empty buzzword steps:** Do not use non-mathematical section titles ("Atomic Conclusion", "Context
    Validation", "Final Transformation", …) with one or two vague sentences. Every step must add real
    explanation (intuition, definition, or a line of reasoning).
  - Avoid filler words ("clearly", "obviously", "trivially") without substantive detail; replace them with
    the actual mathematical justification.
  - Use multiple distinct steps (goal → plan → lemmas/tactics → link to the proof script). Do not collapse
    the entire informal argument into a single short paragraph.
  - **Teaching value:** Explain so a motivated lay reader **learns** something — intuition for the statement,
    what the symbols mean in words, and (when helpful) one tiny numeric example. Even when the formal proof is
    a short Mathlib `exact`, spell out **what** the named lemma says in plain language and **why** it matches
    the goal (including **which side** of an equality is which). Do **not** pad with meta-commentary ("the
    instructions say to use the library", "we avoid induction per policy") instead of mathematics.
  - Informal "text" must be plain English prose only: no LaTeX (no $...$), no raw Unicode math operators.
    You MAY use digits for concrete arithmetic (e.g. 22 + 120 = 142, or "100") instead of spelling every
    number in words — precision and readability matter more than spelling out "one hundred".
    Spell out structural relations in words when describing types and goals (e.g. "less than or equal to");
    keep Lean identifiers and tactic names in backticks when needed (e.g. `le_refl`).
- "proof_script": string, the COMPLETE contents of **Submission.lean** — **imports**, then **`namespace Submission`**
  / **`end Submission`** wrapping the theorem (required; see next bullet).

  Formal proof style in Submission.lean — **correctness first** (informal depth is separate; see above):
  - **Lake workspace contract (must satisfy):** The project also builds **Solution.lean**, which does
    `import Submission` and **`exact Submission.<theorem_name>`**. Therefore the proved theorem **must** be declared
    **`inside namespace Submission`** (same theorem name as in the challenge). If you emit a **top-level** `theorem`
    with no namespace, `Submission.<name>` is **unknown** and the full build fails with errors like
    `Unknown identifier Submission.<name>` even when Submission.lean alone seemed to compile.
  - **Mathlib is allowed:** Prefer lemmas, `simp`, `rw`, `ring`, and short `exact` chains when they match the goal.
    A reliable proof beats a long wrong one. You are **not** required to avoid lemmas to look "more manual."
  - **Expand when appropriate:** Use `calc`, `induction … with`, `cases`, long rewrite chains when no lemma fits,
    or when the structured Lean proof is genuinely clearer — not as padding when a standard lemma already proves
    the goal (put that pedagogical work in **`reasoning_steps`** instead).
  - **Induction / calc:** When using induction or multi-step `calc`, name branches (`| zero =>`, `| succ … ih =>`),
    cite lemmas (`Nat.mul_add`, etc.), and use `--` comments on non-trivial steps.
  - **Lean comments:** Use `-- …` before major blocks; when closing with a lemma, note direction (e.g. `.symm`,
    `←`) if it is easy to get wrong.
  - **Existentials and Mathlib names:** The goal's binder syntax matters. Example: `∃ p > N, Nat.Prime p` is not
    the same type as `Nat.exists_infinite_primes N` (which gives `∃ p, N ≤ p ∧ …`). Use a lemma that matches
    strict inequality, or instantiate at `N.succ` / convert with `Nat.succ_le_iff` / `Nat.lt_of_succ_le`, etc.
  - **ℕ multiplication associativity — Lean pitfall:** Mathlib's **`Nat.mul_assoc a b c`** proves
    **`(a * b) * c = a * (b * c)`**. Goals stated as **`a * (b * c) = (a * b) * c`** need the **same fact flipped**:
    use **`exact (Nat.mul_assoc a b c).symm`**, **`rw [← Nat.mul_assoc a b c]`**, or **`symm; exact Nat.mul_assoc …`**.
    A bare **`exact Nat.mul_assoc a b c`** fails when the goal is reversed. **Informally**, still teach associativity
    thoroughly (why grouping does not matter; a small numeric walk-through); the lemma handles Lean, not the reader.
    Manual induction on associativity is fragile because `*` is left-associative (`a * b * 0` is `(a * b) * 0`).
  - **ℝ absolute value / triangle inequality:** To prove **`abs (x - z) ≤ abs (x - y) + abs (y - z)`**, first use
    algebra (`ring` / `linarith`) to rewrite **`x - z` as `(x - y) + (y - z)`**, then apply the inequality
    **`|a + b| ≤ |a| + |b|`**. In current Mathlib this is typically **`abs_add_le a b`**, not bare **`abs_add`** (which
    may not resolve after `import Mathlib`). Alternative one-liner: **`simpa [Real.dist_eq] using dist_triangle x y z`**
    (metric space on `ℝ`). **Informally**, still walk through the "detour through y" picture in words; the formal
    side can stay short.

You MUST include a non-empty "reasoning_steps" array with at least one step whose "text" is non-empty.
(Legacy single-string "reasoning_trace" is not accepted — structured steps only.)

The proof must close the theorem with the SAME name as in the statement.
Do not use sorry, admit, or custom axioms.
"""


class LLMProver:
    def __init__(self, settings: LemmaSettings) -> None:
        self._settings = settings

    async def solve(self, synapse: LemmaChallenge) -> tuple[str, str, list[ReasoningStep] | None]:
        _raise_if_prover_model_is_studio_client_id(self._settings.prover_model)
        user = f"Imports hint: {synapse.imports}\n\nTheorem block:\n{synapse.theorem_statement}\n"
        attempts = int(self._settings.prover_llm_retry_attempts)
        prov = (self._settings.prover_provider or "anthropic").lower()
        if prov == "openai":
            key = self._settings.prover_openai_api_key_resolved()
            if not key:
                return _stub(synapse)
            model = self._settings.prover_model or self._settings.openai_model
            t_out = _httpx_timeout(self._settings)
            sys_prompt = PROVER_SYSTEM
            base_url = self._settings.prover_openai_base_url_resolved()

            async def _openai_call() -> str:
                async with httpx.AsyncClient(timeout=t_out) as http:
                    okw: dict[str, object] = {"api_key": key, "http_client": http}
                    if base_url:
                        okw["base_url"] = base_url
                    client = AsyncOpenAI(**okw)
                    resp = await client.chat.completions.create(
                        model=model,
                        temperature=float(self._settings.prover_temperature),
                        max_tokens=self._settings.prover_max_tokens,
                        messages=[
                            {"role": "system", "content": sys_prompt},
                            {"role": "user", "content": user},
                        ],
                    )
                return resp.choices[0].message.content or ""

            text = await async_llm_retry(
                _openai_call,
                max_attempts=attempts,
                transient_exceptions=TRANSIENT_OPENAI_COMPAT,
            )
        else:
            key = self._settings.anthropic_api_key
            if not key:
                return _stub(synapse)
            model = self._settings.prover_model or self._settings.anthropic_model
            t_out = _httpx_timeout(self._settings)
            sys_prompt = PROVER_SYSTEM

            async def _anthropic_call() -> str:
                AsyncAnthropic = anthropic_async_client_cls()
                client = AsyncAnthropic(api_key=key, timeout=t_out)
                # Many Claude models cap output at 8192; avoid provider errors if PROVER_MAX_TOKENS is higher.
                max_out = min(int(self._settings.prover_max_tokens), 8192)
                msg = await client.messages.create(
                    model=model,
                    max_tokens=max_out,
                    temperature=float(self._settings.prover_temperature),
                    system=sys_prompt,
                    messages=[{"role": "user", "content": user}],
                )
                out = ""
                for block in msg.content:
                    if hasattr(block, "text"):
                        out += block.text
                return out

            text = await async_llm_retry(
                _anthropic_call,
                max_attempts=attempts,
                transient_exceptions=anthropic_transient_exceptions(),
            )
        if self._settings.miner_log_forwards:
            tail = text if len(text) <= 16_000 else text[:8000] + "\n... [truncated] ...\n" + text[-8000:]
            logger.debug("prover raw model output:\n{}", tail)
        try:
            data = _extract_json_obj(text)
        except (json.JSONDecodeError, ValueError):
            logger.warning(
                "prover JSON parse error; raw excerpt:\n{}",
                text[:6000] if text else "<empty>",
            )
            return ("parse_error", "-- prover JSON parse error\n", None)
        return _normalize_prover_payload(data, self._settings)


def _extract_json_obj(text: str) -> dict:
    start = text.find("{")
    end = text.rfind("}")
    if start < 0 or end < start:
        raise ValueError("no json object")
    return json.loads(text[start : end + 1])


_POLICY_FAIL_TRACE = (
    "prover policy violation: JSON must contain a non-empty reasoning_steps array "
    "(at least one step with non-empty text). Legacy reasoning_trace alone is not accepted."
)
_POLICY_FAIL_PROOF = "-- prover policy: missing non-empty reasoning_steps\n"
_POLICY_FAIL_MIN_STEPS = (
    "prover policy violation: reasoning_steps has fewer entries than LEMMA_PROVER_MIN_REASONING_STEPS "
    "(informal exposition required)."
)
_POLICY_FAIL_MIN_CHARS = (
    "prover policy violation: total informal text is shorter than "
    "LEMMA_PROVER_MIN_REASONING_TOTAL_CHARS."
)
_POLICY_FAIL_MIN_PROOF_CHARS = (
    "prover policy violation: proof_script is shorter than LEMMA_PROVER_MIN_PROOF_SCRIPT_CHARS "
    "(detailed Submission.lean required)."
)


def _normalize_prover_payload(
    data: dict,
    settings: LemmaSettings | None = None,
) -> tuple[str, str, list[ReasoningStep] | None]:
    """Require structured informal reasoning; discard model proof on policy failure so verify+judge fail closed."""
    proof_in = str(data.get("proof_script", ""))
    raw_steps = data.get("reasoning_steps")
    if not isinstance(raw_steps, list) or not raw_steps:
        logger.warning(
            "prover JSON missing non-empty reasoning_steps (legacy reasoning_trace is ignored)"
        )
        return (_POLICY_FAIL_TRACE, _POLICY_FAIL_PROOF, None)

    parsed: list[ReasoningStep] = []
    for item in raw_steps:
        if isinstance(item, dict):
            parsed.append(ReasoningStep.model_validate(item))
        else:
            parsed.append(ReasoningStep(text=str(item)))
    if not any(s.text.strip() for s in parsed):
        logger.warning("prover reasoning_steps had no non-empty text fields")
        return (_POLICY_FAIL_TRACE, _POLICY_FAIL_PROOF, None)

    if settings is not None:
        min_steps = int(settings.prover_min_reasoning_steps or 0)
        min_chars = int(settings.prover_min_reasoning_total_chars or 0)
        total_chars = sum(len(s.text.strip()) for s in parsed)
        if min_steps > 0 and len(parsed) < min_steps:
            logger.warning(
                "prover reasoning_steps count {} below LEMMA_PROVER_MIN_REASONING_STEPS={}",
                len(parsed),
                min_steps,
            )
            return (_POLICY_FAIL_MIN_STEPS, _POLICY_FAIL_PROOF, None)
        if min_chars > 0 and total_chars < min_chars:
            logger.warning(
                "prover informal reasoning length {} below LEMMA_PROVER_MIN_REASONING_TOTAL_CHARS={}",
                total_chars,
                min_chars,
            )
            return (_POLICY_FAIL_MIN_CHARS, _POLICY_FAIL_PROOF, None)

        min_proof = int(settings.prover_min_proof_script_chars or 0)
        if min_proof > 0 and len(proof_in.strip()) < min_proof:
            logger.warning(
                "prover proof_script length {} below LEMMA_PROVER_MIN_PROOF_SCRIPT_CHARS={}",
                len(proof_in.strip()),
                min_proof,
            )
            return (_POLICY_FAIL_MIN_PROOF_CHARS, _POLICY_FAIL_PROOF, None)

    trace = format_reasoning_steps(parsed)
    return trace, proof_in, parsed


def _stub(synapse: LemmaChallenge) -> tuple[str, str, list[ReasoningStep] | None]:
    trace = "stub: no PROVER API key configured"
    stub_steps = [ReasoningStep(title="Setup", text=trace)]
    if "two_plus_two_eq_four" in synapse.theorem_statement:
        proof = """import Mathlib

namespace Submission

theorem two_plus_two_eq_four : (2 : Nat) + 2 = 4 := by rfl

end Submission
"""
        steps = [
            ReasoningStep(title="Observation", text="Goal is equality of natural numbers."),
            ReasoningStep(title="Formal proof", text="Close by reflexivity (rfl)."),
        ]
        return format_reasoning_steps(steps), proof, steps
    return trace, synapse.theorem_statement, stub_steps
