server {
    listen 80;
    server_name live.lemmasub.net;

    root /var/www/lemma-live;

    add_header Access-Control-Allow-Origin "*" always;
    add_header Cache-Control "no-store" always;

    location = /cadence.json {
        try_files /cadence.json =404;
    }

    location = /bounties.json {
        try_files /bounties.json =404;
    }
}
